### ISSUE TITLE
TypeError: Cannot read property 'toAlpha3T' of undefined

### ISSUE THREAD

**Issue by bropat** [cospired/i18n-iso-languages#41]
Here is a quick test case:

```
mkdir testcase
cd testcase

git init
npm init --y

npm i --save-prod @cospired/i18n-iso-languages
npm i -g typescript

mkdir src
cd src
```

Create the file `testcase.ts`with following content:

```typescript
import { isValid as isValidLanguageCode } from "@cospired/i18n-iso-languages"

console.log(`isValidLanguageCode: ${isValidLanguageCode("en")}`);
```

Compile and execute it:

```
tsc testcase.ts

node testcase.js

D:\Projects\private\testcase\node_modules\@cospired\i18n-iso-languages\index.js:265
  return this.toAlpha3T(code) !== undefined;
              ^

TypeError: Cannot read property 'toAlpha3T' of undefined
    at exports.isValid (D:\Projects\private\testcase\node_modules\@cospired\i18n-iso-languages\index.js:265:15)
    at Object.<anonymous> (D:\Projects\private\testcase\src\testcase.js:4:72)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

If I remove the `this.` above, it will work.

**Comment by bropat** [comment]
@e110c0 Let me know if you need something else.
